Modified appliance_time_and_locale_configuration
HewlettPackard/oneview-python pull request #123
Opened 2021-02-03 15:24 UTC by SHANDCRUZ

### Description
changed the python class to new style

### Issues Resolved
[List any issues this PR will resolve. e.g., Fixes #01]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass for Python 2.7+ & 3.4+(`$ tox`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
  - [ ] New endpoints supported are updated in the endpoints-support.md file.
- [ ] Changes are documented in the CHANGELOG file.

2021-02-08 04:55 UTC, VenkateshRavula commented on hpeOneView/resources/settings/appliance_time_and_locale_configuration.py
> +class ApplianceTimeAndLocaleConfiguration(ResourceClient):
The base class should be Resource class

2021-02-08 13:20 UTC, VenkateshRavula commented on examples/appliance_time_and_locale_configuration.py
>  print("\n## Updated appliance time and locale configurations successfully!")
There is no update operation for this resource. So change the print statement as below.
```
print("\n## Changed the appliance time and locale configurations successfully!")
```

2021-02-08 13:34 UTC, VenkateshRavula requested changes
Update changelog and endpoint-support files with this resource. Also modify oneview_client.py file and test_oneview_client.py files respectively.

Refer the below PR - https://github.com/HewlettPackard/oneview-python/pull/28

2021-02-10 12:30 UTC, VenkateshRavula approved these changes
Please modify endpoints file

2021-02-10 12:31 UTC, VenkateshRavula commented on endpoints-support.md
> +|<sub>/rest/appliance/configuration/time-locale</sub>                                     |GET       |  :white_check_mark:   | :white_check_mark:   | :white_check_mark:   |  :white_check_mark:   |  :
keep white_check_mark only for api 2400

2021-02-19 04:11 UTC, yuvirani approved these changes

2021-02-19 04:26 UTC, merged